// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VersionFormat
{
    internal sealed partial class Vsix
    {
        public const string Id = "VersionFormat.322533f3-dec8-48c8-bf5a-51611bfa34d1";
        public const string Name = "VersionFormat";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "CIMSOLUTIONS B.V.";
        public const string Tags = "";
    }
}
